### PR TITLE
add windows vanilla build script

### PR DESCRIPTION
**Pull request by stooke**
add build11.cmd to build vanilla Windows OpenJDK 11.

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Thanks! Looks fine to me.

**Review by jerboaa — CHANGES_REQUESTED** [review]
On second though, could you please also adjust https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/blob/master/tools/search_replace_tag.sh#L56 so that it works for `build11.cmd` too?

**Comment by stooke** [comment]
> On second though, could you please also adjust https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/blob/master/tools/search_replace_tag.sh#L56 so that it works for `build11.cmd` too?

Sorry!  Done.

**Review by jerboaa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
