### PR TITLE
Prepare for 11.0.10 EA builds cycle

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes?
This is early to raise this PR. Just keeping it ready and can be merged later once approved and EA cycle starts.

### CODE REVIEW

**Comment by jhuttana** [comment]
Verified bootjdk change:

$ pushd /opt
$ wget -O jdk-11.0.9_11.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9%2B11/OpenJDK11U-jdk_x64_linux_11.0.9_11.tar.gz"
$ tar -xf jdk-11.0.9_11.tar.gz
$ /opt/openjdk-11.0.9_11/bin/java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11, mixed mode)

**Review by jerboaa — APPROVED** [review]
Looks fine. Please delay merging until the first 11.0.10 EA tag (b01) appears.

**Comment by jhuttana** [comment]
Sure and thank you! for the review.

**Comment by jhuttana** [comment]
I have made the suitable changes after 11.0.9.1+1 release

$ pushd /opt
$ wget -O jdk-11.0.9.1_1.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_x64_linux_11.0.9.1_1.tar.gz"
$ tar -xf jdk-11.0.9.1_1.tar.gz
$ /opt/openjdk-11.0.9.1_1/bin/java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)

**Pull request merged**
